# Generated by Django 6.0.4 on 2026-04-26 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_quote_received', models.BooleanField(default=True)),
                ('email_quote_accepted', models.BooleanField(default=True)),
                ('email_quote_rejected', models.BooleanField(default=True)),
                ('email_message_received', models.BooleanField(default=True)),
                ('email_review_received', models.BooleanField(default=True)),
                ('email_job_completed', models.BooleanField(default=True)),
                ('email_job_cancelled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_prefs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification_preferences',
            },
        ),
    ]
