# Generated by Django 6.0.4 on 2026-04-25 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='klientprofile',
            name='city',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='klientprofile',
            name='default_address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
