# Generated by Django 6.0.4 on 2026-04-26 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_klientprofile_city_klientprofile_default_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freelancerprofile',
            name='avatar_url',
        ),
        migrations.RemoveField(
            model_name='klientprofile',
            name='avatar_url',
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/freelancer/'),
        ),
        migrations.AddField(
            model_name='klientprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/klient/'),
        ),
    ]
