# Generated by Django 6.0.4 on 2026-04-25 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('name_en', models.CharField(blank=True, default='', max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('icon', models.CharField(blank=True, default='', help_text="Identifier for the frontend icon (e.g. 'bolt', 'wrench').", max_length=40)),
                ('description', models.TextField(blank=True, default='')),
                ('sort_order', models.PositiveSmallIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalog.category')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'db_table': 'categories',
                'ordering': ('sort_order', 'name'),
                'indexes': [models.Index(fields=['is_active', 'sort_order'], name='categories_is_acti_3acc57_idx')],
            },
        ),
    ]
