# Generated by Django 6.0.4 on 2026-04-25 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_seed_albanian_categories'),
        ('profiles', '0002_klientprofile_city_klientprofile_default_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('pricing_model', models.CharField(choices=[('hourly', 'Me orë'), ('fixed', 'Çmim fiks'), ('quote', 'Me ofertë')], default='hourly', max_length=10)),
                ('price_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='ALL', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='catalog.category')),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='profiles.freelancerprofile')),
            ],
            options={
                'db_table': 'services',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['category', 'is_active'], name='services_categor_6a9f2f_idx'), models.Index(fields=['freelancer', 'is_active'], name='services_freelan_036b44_idx')],
            },
        ),
        migrations.CreateModel(
            name='ServiceArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(default='AL', max_length=2)),
                ('region', models.CharField(blank=True, default='', max_length=100)),
                ('city', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_areas', to='profiles.freelancerprofile')),
            ],
            options={
                'db_table': 'service_areas',
                'ordering': ('city',),
                'indexes': [models.Index(fields=['country', 'city'], name='service_are_country_3788c5_idx')],
                'constraints': [models.UniqueConstraint(fields=('freelancer', 'country', 'city'), name='unique_freelancer_country_city')],
            },
        ),
    ]
