# Generated by Django 6.0.4 on 2026-04-26 13:02

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_update_seed_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicearea',
            name='center_point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, help_text='Auto-populated from city name; SRID 4326 (WGS84).', null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='servicearea',
            name='radius_km',
            field=models.PositiveSmallIntegerField(default=25),
        ),
    ]
