# Generated by Django 6.0.4 on 2026-04-25 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0003_service_servicearea'),
        ('profiles', '0002_klientprofile_city_klientprofile_default_address'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('budget_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('budget_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='ALL', max_length=3)),
                ('address', models.CharField(blank=True, default='', max_length=255)),
                ('city', models.CharField(max_length=120)),
                ('country', models.CharField(default='AL', max_length=2)),
                ('status', models.CharField(choices=[('open', 'E hapur'), ('in_progress', 'Në proces'), ('completed', 'Përfunduar'), ('cancelled', 'Anuluar')], default='open', max_length=20)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='catalog.category')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'job_requests',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='ALL', max_length=3)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Në pritje'), ('accepted', 'Pranuar'), ('rejected', 'Refuzuar'), ('withdrawn', 'Tërhequr')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='profiles.freelancerprofile')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='jobs.jobrequest')),
            ],
            options={
                'db_table': 'quotes',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='accepted_quote',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_for_job', to='jobs.quote'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['job', 'status'], name='quotes_job_id_aace1a_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['freelancer', 'status'], name='quotes_freelan_1726d3_idx'),
        ),
        migrations.AddConstraint(
            model_name='quote',
            constraint=models.UniqueConstraint(fields=('job', 'freelancer'), name='unique_quote_per_job_freelancer'),
        ),
        migrations.AddIndex(
            model_name='jobrequest',
            index=models.Index(fields=['status', '-created_at'], name='job_request_status_b7e26b_idx'),
        ),
        migrations.AddIndex(
            model_name='jobrequest',
            index=models.Index(fields=['category', 'status'], name='job_request_categor_763515_idx'),
        ),
        migrations.AddIndex(
            model_name='jobrequest',
            index=models.Index(fields=['city', 'status'], name='job_request_city_fd8250_idx'),
        ),
    ]
